# Generated by Django 6.0.5 on 2026-05-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("fecha", models.DateField()),
                ("hora", models.TimeField()),
                ("motivo", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Pendiente", "Pendiente"),
                            ("Atendida", "Atendida"),
                            ("Cancelada", "Cancelada"),
                        ],
                        default="Pendiente",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
